// Core libraries
import { library } from "@fortawesome/fontawesome-svg-core";

// Solid icons
import {
  faShop,
  faGavel,
  faQuestion,
  faWandSparkles,
  faQuoteLeft,
  faMagnifyingGlass,
  faClock,
  faChevronDown,
  faXmark,
  faGlobe,
  faArrowsLeftRight,
  faFlask,
  faSort,
  faRecordVinyl,
  faChessRook,
  faBookBookmark,
  faArrowUp,
  faFileAudio,
  faCube,
  faImage,
  faCircle,
  faMap,
  faBoxOpen,
  faUser,
  faCircleQuestion,
  faAngleUp,
  faLayerGroup,
  faGripVertical,
  faArrowDown19,
  faPenToSquare,
  faCheck,
  faRotateLeft,
  faLinkSlash,
  faHeart,
  // Don't forget to add it below too!
} from "@fortawesome/free-solid-svg-icons";

// Regular icons
import {
  faHeart as farHeart,
  // Don't forget to add it below too!
} from '@fortawesome/free-regular-svg-icons'

// Add icons
library.add(
  faShop,
  faGavel,
  faQuestion,
  faWandSparkles,
  faQuoteLeft,
  faMagnifyingGlass,
  faClock,
  faChevronDown,
  faCheck,
  faXmark,
  faGlobe,
  faArrowsLeftRight,
  faFlask,
  faSort,
  faRecordVinyl,
  faChessRook,
  faBookBookmark,
  faArrowUp,
  faFileAudio,
  faCube,
  faImage,
  faCircle,
  faMap,
  faBoxOpen,
  faUser,
  faCircleQuestion,
  faAngleUp,
  faLayerGroup,
  faGripVertical,
  faArrowDown19,
  faPenToSquare,
  faRotateLeft,
  faLinkSlash,
  faHeart,
  farHeart,
);
